### ISSUE TITLE
Better wayland support

### ISSUE THREAD

**Issue by Jodell88** [Ippytraxx/gnome-twitch#29]
Currently on wayland a second window is spawned that the video is played in while the controls remain with the main window.

The video showed be played in the main window as it does when using the X server.

**Comment by Ippytraxx** [comment]
Yeah currently in master I am just drawing straight to the X window, so that's why you the player is popping out. Can you try the develop branch where I have rewritten the player using Clutter, which supports Wayland. You might need to add these env variables `GDK_BACKEND=wayland CLUTTER_BACKEND=wayland`

**Comment by Jodell88** [comment]
I tried the develop branch and it plays the video in the window. However, if I use the env variables in your post, I get audio and no video and the program freezes after a few seconds. 

Without the env variables it works but the program animations and video playback is extremely choppy.

**Comment by Ippytraxx** [comment]
This should fix it for the most part, however because of the stack slide transition if you change between channels quickly it might get stuck. I will add an option to disable the stack transition while things are being smoothed out with GTK+/Clutters transition to Wayland.

**Comment by Ippytraxx** [comment]
I just noticed now that fullscreening doesn't work properly, so that's another thing I'll have to look into.

**Comment by Jodell88** [comment]
I tried out the latest changes and the performance is great. Fullscreen seems to be working properly here.

Transitions are still getting stuck but the app is more than usable now.

Thanks!

**Comment by Jodell88** [comment]
An amusing bug

![screenshot from 2015-10-14 02-43-09](https://cloud.githubusercontent.com/assets/2472132/10476630/8cb32a2e-721d-11e5-9947-1fff0b2fc446.png)

**Comment by Ippytraxx** [comment]
More info on this? When does this happen? Does it happen often? I haven't encountered this myself yet.

**Comment by Jodell88** [comment]
That was the first and only time it happened so far. The window could be moved an even put on separate workspaces like how it was shown in the screenshot. 

Fullscreening the app fixed the issue.
